---
title: "Courses"
description: |
  A list of good online courses and lectures.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

So, there's a few really good courses on YouTube. You almost never have to pay to view good content (most of Udemy's content is shit. Also, why is everything on sale on there all the time?). Here's a list of courses that I have actually done and I found to be really good.

1.  **Andrew Ng CS229** (<https://www.youtube.com/watch?v=UzxYlbK2c7E&list=PLA89DCFA6ADACE599>) (the OG ones with the blue board!)

2.  **Stanford CS231N** (<https://www.youtube.com/watch?v=vT1JzLTH4G4&list=PLC1qU-LWwrF64f4QKQT-Vg5Wr4qEE1Zxk>)

3.  **Companion Videos to "Deep Learning" by Ian Goodfellow** (<https://www.youtube.com/watch?v=vi7lACKOUao&list=PLsXu9MHQGs8df5A4PzQGw-kfviylC-R9b>)

4.  **Stanford CS224U** (<https://www.youtube.com/watch?v=tZ_Jrc_nRJY&list=PLoROMvodv4rObpMCir6rNNUlFAn56Js20>)

5.  **Harvard's Abstract Algebra** (<https://www.youtube.com/playlist?list=PLelIK3uylPMGzHBuR3hLMHrYfMqWWsmx5>)

6.  **MIT 9.520 Statistical Learning Theory and Applications** (<https://www.youtube.com/watch?v=4nPABKIuYKo&list=PLyGKBDfnk-iB4Xz_EAJNEgGF5I-6OzRNI>)

7.  **Stanford Convex Optimization** (<https://www.youtube.com/watch?v=McLq1hEq3UY&list=PL3940DD956CDF0622>)

8.  **CMU Statistical Machine Learning** (<https://www.youtube.com/watch?v=Z1cSby8ZzhA&list=PLjbUi5mgii6B7A0nM74zHTOVQtTC9DaCv>) (as a supplement to 9.520)

    > If you find the statistical learning part too difficult, don't skip it. MIT CBMM hosts a workshop called RegML. It's a bootcamp sort of thing. They go through the statistics in a really short time and it's easier. Look it up!

9.  **CMU Deep Learning** (just the beginning. I found it too slow) (<https://www.youtube.com/watch?v=0Oqpax2Q2hc&list=PLp-0K3kfddPzCnS4CqKphh-zT3aDwybDe>)

10. **TODO**: CS234 - Reinforcement Learning (<https://www.youtube.com/watch?v=FgzM3zpZ55o&list=PLoROMvodv4rOSOPzutgyCTapiGlY2Nd8u>)

11. **TODO**: CS330 - Deep Multi-Task and Meta Learning (<https://www.youtube.com/watch?v=0rZtSwNOTQo&list=PLoROMvodv4rMC6zfYmnD7UG3LVvwaITY5>)
