---
title: "Project GANdalf"
description: |
  A short post about a new project I've been thinking about.
author:
  - name: Gunjan Payal
    url: {}
date: 06-02-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Now that I know PyTorch and a shit ton of statistics, I can finally begin to implement shit. So, I went to connectedpapers.com and I searched for the original GANs paper by Ian Goodfellow and looked at papers connected to it that very cited very often. Here's the list I came up with:

In case you run into the same problem as me, i created a python script to rename the files with their title. I was too lazy to download Mendeley. It's on my GitHub. Whatever.

1.  High-Resolution Image Synthesis and Semantic Manipulation with Conditional GANs.pdf

2.  Deep Generative Stochastic Networks Trainable by Backprop.pdf

3.  Reducing the Dimensionality of Data with Neural Networks.pdf

4.  Adversarial Autoencoders.pdf

5.  Conditional Image Synthesis with Auxiliary Classiﬁer GANs.pdf

6.  Progressive Growing Of Gans For Improved Quality, Stability, And Variation.pdf

7.  Learning To Generate Samples From Noise Through Infusion Training.pdf

8.  Generative Moment Matching Networks.pdf

9.  GANs Trained by a Two Time-Scale Update Rule Converge to a Local Nash Equilibrium.pdf

10. DualGAN: Unsupervised Dual Learning for Image-to-Image Translation.pdf

11. Conditional Generative Adversarial Nets.pdf

12. Perceptual Losses for Real-Time Style Transfer and Super-Resolution.pdf

13. Improved Techniques for Training GANs.pdf

14. Generative Adversarial Text to Image Synthesis.pdf

15. Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network.pdf

16. Deep Generative Image Models using a Laplacian Pyramid of Adversarial Networks.pdf

17. Why Are Deep Nets Reversible.pdf

18. Unsupervised Representation Learning With Deep Convolutional Gans.pdf

19. Image-to-Image Translation with Conditional Adversarial Networks.pdf

20. Variational Walkback: Learning a Transition Operator as a Stochastic Recurrent Net.pdf

21. StackGAN: Text to Photo-realistic Image Synthesis with Stacked Generative Adversarial Networks.pdf

So, here's the goal. Implement all of these papers. Simple. Let's give it a deadline. 4th July sounds good. So, I have one month to implement all of these papers.

I'm about to die from sleep deprivation now. Ciao.
